#!/usr/bin/env python3
from __future__ import annotations

import sys

from core.bootstrap.self_heal import bootstrap_then_run_main


if __name__ == "__main__":
    raise SystemExit(bootstrap_then_run_main(sys.argv[1:]))
